#!/usr/bin/env bash

export CONTECO_LABEL="package.metrics_monitor - ModEco"
export CONTECO_DESCRIPTION="The ModEco Metrics Monitor module package based on ElasticSearch Heartbeat."

export CONTECO_TYPE="package"
export CONTECO_NAME="metrics_monitor"
export CONTECO_TAG="7.8.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
